FROM python:3.13-slim
WORKDIR /app

COPY requirements.txt .

RUN apt-get update && \
apt-get install -y git && \
rm -rf /var/lib/apt/lists/* && \
pip install --no-cache-dir --root-user-action=ignore -r requirements.txt

# copy the package
COPY ingestion ./ingestion

CMD ["python", "-m", "ingestion.markdown_ingester"]